apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bottle.name }}
  labels:
    name: {{ .Values.bottle.name }}
spec:
  replicas: {{ .Values.bottle.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.bottle.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.bottle.label }}
    spec:
      containers:
      - name: {{ .Values.bottle.name }}
        image: {{ .Values.bottle.image }}
        imagePullPolicy: {{ .Values.bottle.pullPolicy }}
        volumeMounts:
          - name: {{.Values.volume.name }}
            mountPath: {{ .Values.volume.mountPath }}
      volumes:
      - name: {{ .Values.volume.name }}  
        hostPath: 
          path: {{ .Values.volume.hostPath }}
          type: {{ .Values.volume.type }}
      restartPolicy: {{ .Values.bottle.restartPolicy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vue.name }}
  labels:
    name: {{ .Values.vue.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.vue.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.vue.name }}
    spec:
      containers:
      - name: {{ .Values.vue.name }}
        image: {{ .Values.vue.image }}
        imagePullPolicy: {{ .Values.vue.pullPolicy }}
      restartPolicy: {{ .Values.vue.restartPolicy }}