apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vue.name }}
  labels:
    service: {{ .Values.vue.name }}
spec:
  selector:
    app: {{ .Values.vue.name }}
  ports:
  - port: {{ .Values.vue.port }}
    targetPort: {{ .Values.vue.targetPort }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bottle.name }}
  labels:
    service: {{ .Values.bottle.name }}
spec:
  selector:
    app: {{ .Values.bottle.label }}
  ports:
  - port: {{ .Values.bottle.port }}
    targetPort: {{ .Values.bottle.targetPort }}
  type: {{ .Values.service.type }}